config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'

  # devise_for :users
    # devise_for :users, controllers: {
    #   sessions: 'users/sessions'
    # }
devise_for :users, controllers: {registrations: "users/registrations", sessions: 'users/sessions'}

  # devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}



root :to => "users#index"




    resources :users do
      # resources :goals
      # resources :logs do

      resources :foods
      resources :workouts
      resources :sleeps
      resources :waters
      resources :goals
      resources :logs
    # end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :logs
  has_many :foods
  has_many :waters
  has_many :sleeps
  has_many :workouts
  has_many :goals

accepts_nested_attributes_for :logs, :allow_destroy => true
accepts_nested_attributes_for :goals, :allow_destroy => true
accepts_nested_attributes_for :workouts, :allow_destroy => true
accepts_nested_attributes_for :waters, :allow_destroy => true
accepts_nested_attributes_for :foods, :allow_destroy => true
accepts_nested_attributes_for :sleeps, :allow_destroy => true
  # attr_accessible :email, :password, :password_confirmation

  # attr_accessor :password
  # before_save :encrypt_password

  # validates_confirmation_of :password
  # validates_presence_of :password, :on => :create
  # validates_presence_of :email
  # validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def fullname
  "#{firstName} #{lastName}"
end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/Users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super

  end

  # POST /resource
  def create
    super

  end

  # GET /resource/edit
  def edit
    super

  end

  # PUT /resource
  def update
    super

  end

  # DELETE /resource
  def destroy
    super

  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/Users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super

  end

  # POST /resource/sign_in
  def create
    super


  end
  #
  # DELETE /resource/sign_out
  def destroy
    super

  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
  
    def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/Users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all

  end
end

app/views/users/edit.html.erb
user.email, user.password, user.password_confirmation, user.name, user.username, user.challenge_id, user.created_at, user.updated_at)


<%= form_for @user do |f| %>
</br>
<%= f.label  :firstName, "First Name" %>
<%= f.text_field :firstName %>
</br>
<%= f.label  :LastName, "Last Name" %>
<%= f.text_field :LastName %>
</br>
<%= f.label  :startWeight, "Start Weight" %>
<%= f.text_field :startWeight %>
</br>
<%= f.label  :goalWeight, "Goal Weight" %>
<%= f.text_field :goalWeight %>
</br>

  <%=f.submit %>
  <% end %>

app/views/users/index.html.erb
<%= javascript_pack_tag 'application' %>
<h1>users#index</h1>
  <%= react_component( 'Users', { data: @users} )%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

app/views/users/show.html.erb
<h1> <%= @user.firstName %> <%= @user.LastName %> </h1>
  <p> Start Weight: <%= @user.startWeight %></p>
  <p> Goal Weight:<%= @user.goalWeight %></p>

  <button><%=link_to "Edit Profile", edit_user_path(@user, @logs) %></button></br>
    </br><%= button_to "Logs", user_logs_path(@user, @logs) %>
  <%= button_to "Goals", user_goals_path(@user, @goals) %>
  <%= button_to "Sleeps", user_sleeps_path(@user, @sleeps) %>
  <%= button_to "Foods", user_foods_path(@user, @foods) %>
  <%= button_to "Waters", user_waters_path(@user, @waters) %>
  <%= button_to "Workouts", user_workouts_path(@user, @workouts) %>
  <%= button_to "Logs", user_logs_path(@user, @logs) %>

  </br><%= link_to "Log Index", user_logs_path(@user) %></br>
  <button><%= link_to "See your Logs", user_logs_path(@user, @logs) %></button></br>
      <% @user.logs.each do |log| %>
  <% end %>


<h1>Sleeps</h1>
    <table>
      <thead>
        <tr>
          <th>Sleep id</th>
          <th>Sleep goalMet</th>
          <th>Sleep Point</th>
          <th>Sleep Goal</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.sleeps.each do |sleep| %>
          <tr>
            <td></td>
            <td><%= sleep.id %></td>
            <td><%= sleep.goalMet %></td>
            <td><%= sleep.sleepPoint %></td>
            <td><%= sleep.sleepGoal %></td>
            <td><%= link_to 'Show', user_sleep_path(@user, sleep) %></td>
            <td><%= link_to 'Edit', edit_user_sleep_path(@user, sleep) %></td>
            <td><%= link_to 'Destroy',[@user, sleep] , method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <button><%=link_to "New Sleep", new_user_sleep_path(@user, @sleeps) %></button></br>
<h1>Waters</h1>
    <table>
      <thead>
        <tr>
          <th>Water id</th>
          <th>Water waterDrank</th>
          <th>Water Point</th>
          <th>Water waterPoint</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.waters.each do |water| %>
          <tr>
            <td><%= water.id %></td>
            <td><%= water.waterDrank %></td>
            <td><%= water.point %></td>
            <td><%= water.waterPoint %></td>
            <td><%= link_to 'Show', user_water_path(@user, water) %></td>
            <td><%= link_to 'Edit', edit_user_water_path(@user, water) %></td>
            <td><%= link_to 'Destroy', [@user, water], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <button><%=link_to "Add New Water", new_user_water_path(@user, @waters) %></button></br>
<h1>Foods</h1>
    <table>
      <thead>
        <tr>
          <th>food.id</th>
          <th>food.goalMet</th>
          <th>food.foodPoint</th>
          <th>food.foodGoal</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @user.foods.each do |food| %>
          <tr>

            <td></td>
            <td><%= food.id %></td>
            <td><%= food.goalMet %></td>
            <td><%= food.foodPoint %></td>
            <td><%= food.foodGoal %></td>
            <td><%= link_to 'Show', user_food_path(@user, food) %></td>
            <td><%= link_to 'Edit', edit_user_food_path(@user, food) %></td>
            <td><%= link_to 'Destroy', [@user, food], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <button><%=link_to "Add Food", new_user_food_path(@user, @foods) %></button></br>
<h1>Workouts</h1>
    <table>
      <thead>
        <tr>
          <th>workout id</th>
          <th>workout goalMet</th>
          <th>workout workoutPoint</th>
          <th>workout points</th>
          <th>workout workoutGoal</th>
          <th>workout hours</th>
          <th>workout workoutType</th>
          <th>workout workoutTime</th>
          <th>workout caloriesBurned</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @user.workouts.each do |workout| %>
          <tr>
            <td><%= workout.id %></td>
            <td><%= workout.goalMet %></td>
            <td><%= workout.workoutPoint %></td>
            <td><%= workout.points %></td>
            <td><%= workout.workoutGoal %></td>
            <td><%= workout.hours %></td>
            <td><%= workout.workoutType %></td>
            <td><%= workout.workoutTime %></td>
            <td><%= workout.caloriesBurned %></td>
            <td><%= link_to 'Show', user_workout_path(@user, workout) %></td>
            <td><%= link_to 'Edit', edit_user_workout_path(@user, workout) %></td>
            <td><%= link_to 'Destroy', [@user, workout], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <button><%=link_to "New Workout", new_user_workout_path(@user, @workouts) %></button></br>
<h1>Logs</h1>
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Water</th>
          <th>Sleep</th>
          <th>Workout</th>
          <th>Food</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.logs.each do |log| %>
          <tr>
            <td><%= log.id %></td>
            <td><%= log.water %></td>
            <td><%= log.sleep %></td>
            <td><%= log.workout %></td>
            <td><%= log.food %></td>
            <td><%= link_to 'Show', user_log_path(@user,log) %></td>
            <td><%= link_to 'Edit', edit_user_log_path(@user,log) %></td>
            <td><%= link_to 'Destroy', [@user,log],  method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <button><%=link_to "Add to Log", new_user_log_path(@user, @logs) %></button></br>
<h1>Goals</h1>
  <!-- <p>Goal</p> -->
  <!-- <#%= link_to "Goal Index", user_goal_path(@user) %>
  <#%= link_to "Goal Show", user_goals_path(@user) %>
  <#%= link_to "Add to Goal", new_user_goal_path(@user) %>
  <#%= link_to "Edit to Goal", edit_user_goal_path(@user) %> -->

    <%= react_component 'User', { data: @user} %>