config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'

  # devise_for :users
    # devise_for :users, controllers: {
    #   sessions: 'users/sessions'
    # }
devise_for :users, controllers: {registrations: "users/registrations", sessions: 'users/sessions'}

  # devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}



root :to => "users#index"




    resources :users do
      # resources :goals
      # resources :logs do

      resources :foods
      resources :workouts
      resources :sleeps
      resources :waters
      resources :goals
      resources :logs
    # end
  end

end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  # belongs_to :log
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @user = User.find(params[:user_id])
    @goals = @user.goals.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @user = User.find(params[:user_id])
    @goal = @user.goals.find(goal_params[:id])
  end

  # GET /goals/new
  def new
    @user = User.find(params[:user_id])
    @goal = @user.goals.new
  end

  # GET /goals/1/edit
  def edit
    @user = User.find(params[:user_id])
    @goal = @user.goals.find(goal_params[:id])
  end

  # POST /goals
  # POST /goals.json
  def create
    @user = User.find(params[:user_id])
    @goal = @user.goals.create!(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to user_goals_path, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    @user = User.find(params[:user_id])
    @goal = @user.goals.find(goal_params[:id])
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to user_goals_path, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    # @user = User.find(params[:user_id])
    # @goal = @user.goals.find(goal_params[:id])
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to user_goals_path, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @user = User.find(params[:user_id])
      @goal = @user.goals.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def goal_params
    #   params.fetch(:goal, {})
    # end

    def goal_params
      params.require(:goal).permit(:id, :created_at, :updated_at, :user_id, :waterGoal, :waterPoint, :weightGoal, :weightPoint, :sleepPoint, :sleepGoal, :workoutGoal, :workoutPoint, :foodPoint, :foodGoal)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for [@user, @goal], :html => { :multipart => true,  :class => "pictureInput" } do |f| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.hidden_field :user_id, :value => @user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', user: @user, goal: @goal %>

<%= link_to 'Show', user_goal_path(@user, @goal) %> |
<%= link_to 'Back', user_goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goals</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= link_to 'Show', user_goal_path(@user, @goal) %></td>
        <td><%= link_to 'Edit', edit_user_goal_path(@user, @goal) %></td>
        <td><%= link_to 'Destroy', [@user, @goal], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', user_new_goal_path %>
<%= link_to 'Back', user_path(@user) %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', user: @user, goal: @goal %>

<%= link_to 'Back', user_goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_goal_path(@user, @goal) %> |
<%= link_to 'Back', user_goals_path(@user, @goal) %>