config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'

  # devise_for :users
    # devise_for :users, controllers: {
    #   sessions: 'users/sessions'
    # }
devise_for :users, controllers: {registrations: "users/registrations", sessions: 'users/sessions'}

  # devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}



root :to => "users#index"




    resources :users do
      # resources :goals
      # resources :logs do

      resources :foods
      resources :workouts
      resources :sleeps
      resources :waters
      resources :goals
      resources :logs
    # end
  end

end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  has_many :foods
  has_many :waters
  has_many :sleeps
  has_many :workouts
  has_many :goals


  accepts_nested_attributes_for :goals, :allow_destroy => true
  accepts_nested_attributes_for :workouts, :allow_destroy => true
  accepts_nested_attributes_for :waters, :allow_destroy => true
  accepts_nested_attributes_for :foods, :allow_destroy => true
  accepts_nested_attributes_for :sleeps, :allow_destroy => true



  def log_id
    log_id = @log.id
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  # before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @user = User.find(params[:user_id])
    @logs =@user.logs.all

    # @waters = @user.logs.waters
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @user = User.find(params[:user_id])
    @log = @user.logs.find(log_params[:id])
  end

  # GET /logs/new
  def new
    @user = User.find(params[:user_id])
    @log = @user.logs.new
  end


  # POST /logs
  # POST /logs.json
  def create
    @user = User.find(params[:user_id])
    # @log =  @user.logs.create!(log_params)
    @log =  @user.logs.create!

    respond_to do |format|
      if @log.save
        format.html { redirect_to user_logs_url, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /logs/1/edit
  def edit
    @user = User.find(params[:user_id])
    @log = @user.logs.find(params[:id])
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    @user = User.find(params[:user_id])
    @log = @user.logs.find(params[:id])
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to user_logs_url, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    # @user = User.find(params[:user_id])
    # @log = @user.logs.find(params[:id])
    @log.destroy
    respond_to do |format|
      format.html { redirect_to user_logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_log
    #   @user = User.find(params[:user_id])
    #   @log = @user.logs.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def log_params
    #   params.require(:log).permit(:water, :sleep , :workout, :food, :goal)
    # end
    def log_params
      params.require(:log).permit(:id, :date, :water, :sleep , :workout, :food, :goal, :point, :totalPoints, :weightStatus, :weeklyGoalMet, :created_at , :updated_at,  :user_id, :goal_id)
    end

    def user_params
      params.require(:user).permit(:id,
      :firstName, :LastName, :startWeight, :goalWeight, :email, :password, :password_confirmation, :username, :created_at, :updated_at)
    end

    def food_params
      params.require(:food).permit(:id, :date, :goalMet, :foodPoint , :foodGoal, :created_at , :updated_at,  :user_id)
    end

    def sleep_params
      params.require(:sleep).permit(:id, :date, :goalMet, :sleepGoal, :sleepPoint)
    end

    def water_params
      params.require(:water).permit(:id, :date, :waterDrank, :waterGoal, :point, :goalMet, :waterPoint, :created_at, :updated_at, :user_id)
    end

    def water_params
      params.require(:workout).permit(:id, :date, :hours, :workoutGoal, :point, :goalMet, :workoutPoint, :workoutType, :caloriesBurned, :workedoutTime, :created_at, :updated_at, :user_id)
    end

    def goal_params
      params.require(:goals).permit(:id, :created_at, :updated_at, :user_id, :waterGoal, :waterPoint, :weightGoal, :weightPoint, :sleepPoint, :sleepGoal, :workoutGoal, :workoutPoint, :foodPoint, :foodGoal)
    end

end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_for [@user, @log], :html => { :multipart => true,  :class => "pictureInput" } do |f| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <%= f.hidden_field :user_id, :value => @user.id %>

  <div class="field">
    <%= f.label :water %>
    <%= f.text_field :water %>
  </div>

  <div class="field">
    <%= f.label :sleep %>
    <%= f.text_field :sleep %>
  </div>

  <div class="field">
    <%= f.label :workout %>
    <%= f.text_field :workout %>
  </div>

  <div class="field">
    <%= f.label :food %>
    <%= f.text_field :food %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', user: @user, log: @log %>

<%= link_to 'Show', user_log_path(@user, @log) %> |
<%= link_to 'Back', user_logs_path(@user, @log) %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logs</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Water</th>
      <th>Sleep</th>
      <th>Workout</th>
      <th>Food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.logs.each do |log| %>
      <tr>
        <td><%= log.id %></td>
        <td><%= log.water %></td>
        <td><%= log.sleep %></td>
        <td><%= log.workout %></td>
        <td><%= log.food %></td>
        <td><%= link_to 'Show', user_log_path(@user,log) %></td>
        <td><%= link_to 'Edit', edit_user_log_path(@user,log) %></td>
        <td><%= link_to 'Destroy', [@user,log],  method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Log', new_user_log_path %>
<%= button_to "sleep", user_sleeps_path(@user, @sleeps) %>
<%= button_to "water", user_waters_path(@user,@waters) %>
<%= button_to "food", user_foods_path(@user, @foods) %>
<%= button_to "workout", user_workouts_path(@user, @workouts) %>

<%= link_to 'Back', user_path(@user) %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', user: @user, log: @log %>

<%= link_to 'Back', user_logs_path(@user, @log) %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Water:</strong>
  <%= @log.water %>
</p>

<p>
  <strong>Sleep:</strong>
  <%= @log.sleep %>
</p>

<p>
  <strong>Workout:</strong>
  <%= @log.workout %>
</p>

<p>
  <strong>Food:</strong>
  <%= @log.food %>
</p>

<%= link_to 'Edit', edit_user_log_path(@log) %> |
<%= link_to 'Back', user_logs_path %>